'''
  ******************************************************************************************
      Assembly:                Guro
      Filename:                __init__.py
      Author:                  Terry D. Eppler
      Created:                 08-24-2026

      Last Modified By:        Terry D. Eppler
      Last Modified On:        08-24-2026
  ******************************************************************************************
  <copyright file="__init__.py" company="Terry D. Eppler">

         __init__.py
         Copyright ©  2024  Terry Eppler

     Permission is hereby granted, free of charge, to any person obtaining a copy
     of this software and associated documentation files (the “Software”),
     to deal in the Software without restriction,
     including without limitation the rights to use,
     copy, modify, merge, publish, distribute, sublicense,
     and/or sell copies of the Software,
     and to permit persons to whom the Software is furnished to do so,
     subject to the following conditions:

     The above copyright notice and this permission notice shall be included in all
     copies or substantial portions of the Software.

     THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
     INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
     FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
     IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
     DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
     ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
     DEALINGS IN THE SOFTWARE.

     You can contact me at:  terryeppler@gmail.com or eppler.terry@epa.gov

  </copyright>
  <summary>
    Guro instruction prompt package.
  </summary>
  ******************************************************************************************
 '''

from .audio import *
from .image import *
from .text import *

# ----- Public API -----

__all__: tuple[ str, ... ] = (
	'ACADEMIC_WRITER', 'PROMPT_GENERATOR', 'AUTHOR_EMULATOR', 'BUDGET_ANALYST', 'ARTSY_FARTSY',
	'AGENDA_MAKER', 'ADAPTIVE_ANALYST', 'ASCII_ARTIST', 'BUSINESS_ANALYST', 'BUSINESS_PLANNER',
	'BUSINESS_RESEARCHER', 'CHAIN_OF_DENSITY', 'CHECKLIST_CREATOR', 'CODE_REVIEWER',
	'COGNITIVE_PROFILER', 'COMPANY_RESEARCHER', 'COURSE_CREATOR', 'CRITICAL_THINKER', 'DATA_CLEANER',
	'DATA_FARMER', 'DATA_PLUMBER', 'DATA_SCIENTIST', 'DATASET_ANALYZER', 'DATA_VISUALIZER',
	'DECISION_MAKER', 'DEPENDENCY_INDENTIFIER', 'DOCUMENT_INTERROGATOR', 'DOCUMENT_SUMMARIZER',
	'EDUCATIONAL_WRITER', 'EMAIL_ANALYST', 'ENTERTAINMENT_ADVISOR', 'ESSAY_WRITER',
	'EVALUATION_EXPERT', 'EXECUTIVE_ASSISTANT', 'EXPERT_PROGRAMMER', 'FEATURE_DEPARTMENT',
	'FINANCIAL_PLANNER', 'FORM_BUILDER', 'GEOGRAPHY_GURU', 'HOW_TO_BUILDER', 'INTERVIEW_COACH',
	'INVESTMENT_ANALYST', 'JACK_OF_ALL_TRADES', 'KEYWORD_GENERATOR', 'MANAGEMENT_CONSULTANT',
	'MARKET_FORECASTER', 'MARKET_PLANNER', 'MARKET_RESEARCHER', 'MATHY_MAGICIAN',
	'MEDIA_PROFILE_DESIGNER', 'MEETING_OPTIMIZER', 'MEETING_SUMMARIZER', 'MULTI_PROFESSOR',
	'PDF_PARSER', 'PERSONNAL_ASSISTANT', 'POWER_POINT_ANALYST', 'QUICK_PROBLEM_SOLVER',
	'PROMPT_ENGINEER', 'PROJECT_ARCHITECH', 'PROJECT_PLANNER', 'PROMPT_ENHANCER', 'PROMPT_EVALUATOR',
	'PROMPT_REFINER', 'PROOF_READER', 'REASONING_ANALYST', 'RESEARCH_EXPERT',
	'REQUIREMENTS_GENERATOR', 'RESUME_BUILDER', 'RESUME_WRITER', 'REVENUE_PROJECTOR',
	'ROOT_CAUSE_ANALYZER', 'SEARCH_OPTIMIZED_WRITER', 'SEARCH_OPTIMIZER', 'SQL_ANALYST',
	'STRATEGIC_THINKER', 'STRUCTURED_PROBLEM_SOLVER', 'SUSTAINABILITY_PLANNER', 'TASK_PLANNER',
	'TEACHING_ASSISTANT', 'TECH_SUPPORT_ANALYST', 'TRAINING_CONTENT_DESIGNER',
	'TRAINING_PROGRAM_DESIGNER', 'TRAINING_PLANNER', 'TRAINING_WHEELS', 'WEB_DESIGNER',
	'WEB_SEARCH_OPTIMIZER', 'WRITING_EDITOR', 'YOUTUBE_SCRIBE', 'YOUTUBE_SUMMARIZER', 'DATA_ANALYST',
	'COMPLEX_PROBLEM_ANALYST', 'BRAIN_STORMER', 'LEGAL_ANALYST', 'NEWSLETTER_WRITER',
	'RESEARCH_ANALYST', 'RED_TEAM_ANALYST', 'AUTOMATION_ANALYST', 'BOOK_SUMMARIZER',
	'EXPLORATORY_DATA_ANALYZER', 'SPEECH_WRITER', 'RANDOM_WRITER', 'WEALTH_ANALYST',
	'FINANCIAL_ADVISOR', 'FINANCIAL_ANALYST', 'DASHBOARD_ANALYST', 'PBI_ANALYST', 'EXCEL_ANALYST',
	'EXCEL_NINJA', 'PBI_EXPERT', 'STATISTICS_ANALYST', 'INNOVATION_ANALYST', 'WHAT_IF_ANALYST',
	'PROCUREMENT_ANALYST', 'OUTLOOK_ANALYST', 'PYTHON_ANALYST', 'DATA_BRO', 'APPORTIONMENT_ANALYST',
	'TOPIC_RESEARCHER', 'SCHEDULE_X_ANALYST', 'APPROPRIATIONS_ANALYST', 'RESEARCH_EVALUATOR',
	'GUARDRAIL_GOVENOR', 'PORTRAIT_ENHANCER', 'NICHE_RESEARCHER', 'EMAIL_ANALYST_2',
	'DATABASE_SPECIALIST', 'CRITICAL_REASONING_ANALYST', 'POWER_QUERY_ANALYST',
	'APPROPRIATION_CROSS_WALKER', 'SPONSOR', 'POWER_POINTER', 'SENTIMENT_ANALYST', 'BUDGET_BUDDY',
	'PROCESS_ENGINEER', 'ANALYTICS_ENGINEER', 'DATA_PLATFORM_ARCHITECT', 'DATA_ENGINEER',
	'DATA_PLATFORM_ARCHITECT_2', 'AI_GOVENANCE_AGENT', 'COMPLIANCE_ANALYST', 'REGULATORY_ANALYST',
	'ALL_AROUND_WRITER', 'TECHNICAL_WRITER', 'SCIENTIFIC_WRITER', 'HUMANIZER', 'DEEP_RESEARCH_AGENT',
	'REASONING_SPECIALIST', 'AUTONOMOUS_WEB_ANALYST', 'MULTIMODAL_ANALYST', 'DATA_ANALYSIS',
	'GOOGLE_WORKSPACE_AUTOMATION_ARCHITECT', 'PROMPT_INJECTION_GUARDIAN', 'THREAT_DETECTION_ENGINEER',
	'PROMPT_3D_GENERATION_ARTIST', 'HTML_NATIVE_VIDEO_ARCHITECT', 'AGENTIC_VIDEO_EDITING_ENGINEER',
	'CINEMATOGRAPHY_SCENE_CREATOR', 'LOCAL_FIRST_VOICE_I_O_ARCHITECT',
	'GENERATIVE_AUDIO_PROMPT_ENGINEER', 'PDF_TRANSLATOR',
	'TECHNICAL_TRANSLATOR_AND_LOCALIZATION_ENGINEER', 'REALISTIC_IMAGE_JSON_PROMPT',
	'TYPOGRAPHIC_PORTRAIT_CREATOR', 'PROMPT_3D_AVATAR_CREATOR', 'VECTOR_POSTER_CREATOR',
	'MODERN_WEB_DEVELOPMENT_ASSISTANT', 'CREATIVE_DIGITAL_ARTIST', 'DARK_STYLE_IMAGE_CREATOR',
	'HIGH_CONTRAST_STENCIL_POSTER_MAKER', 'ICON_CREATOR', 'LEGO_CHARACTER_CREATOR', 'LOGO_CREATOR',
	'PORTRAIT_MAKER', 'PROFESSIONAL_IMAGE_ENHANCER', 'STICKER_MAKER', 'WHITEBOARD_DESIGNER',
	'WHITEBOARD_INFOGRAPHIC_CREATOR', 'GENERAL_PURPOSE_TRANSLATOR',
	'TECHNICAL_DOCUMENTATION_TRANSLATOR', 'AI_DATASET_TRANSLATOR', 'LEGAL_TRANSLATOR',
	'REAL_TIME_CHAT_TRANSLATOR', 'LOCALE_TRANSLATOR', 'SOURCE_CODE_TRANSLATOR', 'OCR_CLEANER',
	'RAG_TRANSLATOR', 'LITERARY_TRANSLATOR', 'YOU_TUBE_TRANSCRIBER', 'VERBATIM_TRANSCRIBER',
	'LEGAL_TRANSCRIBER', 'TECHNICAL_MEETING_TRANSCRIBER', 'INTERVIEW_TRANSCRIBER',
	'MEDICAL_TRANSCRIPTION_ASSISTANT', 'TRANSCRIPTION_EDITOR', 'AUDIO_DIAGNOSTIC_TRANSCRIBER',
	'MULTILINGUAL_TRANSLATION_TRANSCRIBER', 'DEPOSITION_TRANSCRIBER', 'ALL_PURPOSE_TRANSCRIBER',
	'TTS_SCRIPT_OPTIMIZER', 'NARRATION_DIRECTOR', 'EXECUTIVE_BRIEFING_NARRATOR',
	'INSTRUCTIONAL_NARRATOR', 'AUDIOBOOK_NARRATOR', 'PODCAST_HOST', 'ACCESSIBILITY_FOCUSED_NARRATOR',
	'VOICE_STYLE_CONTROLLER', 'MULTI_SPEAKER_DIALOGUE_EDITOR', 'UNIVERSAL_SPEECH_TEMPLATE',
	'CHARACTER_CONCEPT_ARTIST', 'IMAGE_ANALYZER', 'SCREENSHOT_ANALYZER', 'TECHNICAL_DIAGRAM_ANALYZER',
	'IMAGE_QUALITY_REVIEWER', 'OBJECT_ANALYSIS', 'HAZARD_ANALYSIS', 'MAP_ANALYSIS', 'OCR_ANALYSIS',
	'IMAGE_ANALYSIS', 'GENERAL_PURPOSE_IMAGE_EDITOR', 'PRODUCT_PHOTO_EDITOR',
	'PORTRAIT_RETOUCHING_EDITOR', 'BACKGROUND_REPLACER', 'OBJECT_REMOVER',
	'INTERIOR_DESIGN_IMAGE_EDITOR', 'PROPERTY_PHOTO_ENHANCER', 'PHOTO_IMAGE_CLEAN_UP',
	'HISTORICAL_PHOTO_RESTORATION', 'STYLE_TRANSFER_IMAGE_EDITOR', 'TECHNICAL_DIAGRAM_EDITOR',
	'IMAGE_REDACTOR', 'MULTI_STEP_IMAGE_EDITOR', 'PEER_REVIEWER', 'GOVERNANCE_ORCHESTRATOR',
	'SENIOR_ENGINEER', 'CONTEXT_ENGINEER', 'AI_MATHEMATICIAN', 'AI_ENGINEER', 'GOVERNANCE_AGENT',
	'AI_NATIVE_PRODUCT_ARCHITECT', 'CODING_AGENT', 'DATA_GOVERNANCE_ARCHITECT',
	'KNOWLEDGE_BASE_ARCHITECT', 'LLM_ARCHITECT', 'MCP_SERVER_ARCHITECT', 'MULTI_MODAL_AGENT_DESIGNER',
	'MACHINE_LEARNING_ENGINEER', 'MACHINE_LEARNING_SYSTEMS_ARCHITECT', 'QUALITY_ASSURANCE_ENGINEER',
	'SCRUM_MASTER', 'TECHNICAL_DOCUMENTAION_AGENT', 'TOOL_SCHEMA_ARCHITECT',
	'CYBER_SECURITY_RESEARCHER',
)

def names( ) -> tuple[ str, ... ]:
	"""
	Return the instruction names.

	Purpose:
		Provides the names of all publicly exported instructions in declaration
		order.

	Returns:
		tuple[str, ...]: Exported instruction names.
	"""
	return __all__


def values( ) -> tuple[ str, ... ]:
	"""
	Return the instruction values.

	Purpose:
		Provides all publicly exported instruction texts in declaration order.

	Returns:
		tuple[str, ...]: Exported instruction text values.
	"""
	return tuple( globals( )[ name ] for name in __all__ )


def items( ) -> tuple[ tuple[ str, str ], ... ]:
	"""
	Return the instruction names and values.

	Purpose:
		Provides all publicly exported instruction names paired with their
		corresponding text values.

	Returns:
		tuple[tuple[str, str], ...]: Instruction name and text pairs.
	"""
	return tuple( (name, globals( )[ name ]) for name in __all__ )


def get( name: str ) -> str:
	"""
	Return an instruction by name.

	Purpose:
		Retrieves a publicly exported instruction using its uppercase member
		name.

	Args:
		name (str): Exported instruction name.

	Returns:
		str: Instruction text associated with the name.

	Raises:
		KeyError: The requested instruction name is not exported.
	"""
	if name not in __all__:
		raise KeyError( f'Instruction "{{name}}" is not defined.' )

	return globals( )[ name ]
